<?php
session_start();
include('../../class/MySqlClass.php');

$conx = new ConxMySQL("localhost","root","","bdaltono");
$sql = "SELECT valor FROM configuracion WHERE item='ie'";
$consulta = $conx->query($sql);
$records = $conx->records_array($consulta);
$ie= $records['valor']; 
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>JourAcademy - ::<?php echo utf8_encode($ie); ?>::</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
		<h1><a>Inicio de Sesión</a></h1>
		<form id="form_122104" class="appnitro"  method="post" action="upuserresponse.php">
					<div class="form_description">
			<h2><?php echo "$ie"; ?></h2>
            <h3>Actualizar Usuario</h3>
			<p>Para actualizar contraseña de usuario en el sistema, complete los siguientes datos</p>
		</div>						
		<ul >
			
		<li id="li_1" >
		<label class="description" for="coddocen">Docente </label>
		<div>
		<select class="element select medium" id="coddocen" name="coddocen"> 
		<?php
			$sql = "SELECT * FROM tbdocente";
			$consulta = $conx->query($sql);
			while($records = $conx->records_array($consulta)){
				echo "<option value='".$records['codigo']."'>".strtoupper($records['n1'])." ".strtoupper ($records['a1'])."</option>";
			}
		?>
		</select>
		</div><p class="guidelines" id="guide_3"><small>Seleccione el docente</small></p> 
		</li>
        <li id="li_2">
        <label class="description" for="pass">Contraseña</label>
		<div>
			<input id="pass" name="pass" class="element text medium" type="password" maxlength="20" value=""/> 
		</div><p class="guidelines" id="guide_2"><small>Ingrese la clave</small></p> 
		</li>
		<li id="li_3">
		<label class="description" for="tp_user">Tipo de usuario </label>
		<span>
			<input id="tp_user_1" name="tp_user" class="element radio" type="radio" value="DO" checked="checked">
            <label class="choice" for="tp_user_1">Docente</label>
            <input id="tp_user_2" name="tp_user" class="element radio" type="radio" value="AD">
            <label class="choice" for="tp_user_2">Administrador</label>
    	</span><p class="guidelines" id="guide_4"><small>Seleccione el tipo de usuario</small></p> 
		</li>
		<li class="buttons">
		    <input type="hidden" name="form_id" value="122104" />
			    
			<input id="saveForm" class="button_text" type="submit" name="saveForm" value="Dar de alta" />
		</li>
			</ul>
		</form>	
        <br />
        <span>
        <a href="../../indexadmin/index.php" class="large button orange" style="font-size: 12px !important;">Regresar</a>
        </span>

		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a><br/>
			Copyright © 2011 - by wiledu[williamcortes10@gmail.com]			
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>