<?php
session_start();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>JourAcademy - ::Colegio Tecnico Militar Almirante Tono Tumaco S.A.S::</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
	<body id="main_body" >
	<div id="content">
		<div id="nav">
			<?php
				include('../../class/MySqlClass.php');
				if(!empty($_POST['coddocen']) && !empty($_POST['pass']) && !empty($_POST['tp_user'])){
					$user = $_POST['coddocen'];
					$pass = md5($_POST['pass']);
					$tipo_user = $_POST['tp_user'];
					$conx = new ConxMySQL("localhost","root","","bdaltono");
					$sql = "SELECT usuario, tipo_user FROM tblogin WHERE usuario='".$user."'";
					$consulta = $conx->query($sql);
					if($conx->get_numRecords($consulta)>0){
					   
                       header('Location: ../../error/errornvuser.php');
						
					}else{
						$sqllog = "INSERT INTO tblogin(usuario,clave,tipo_user) VALUES ('".$user."','".$pass."',".$tipo_user."')";
						$consulta = $conx->query($sqllog);
                        header('Location: ../../sucess.php');
					}
					
				}else{
					header('Location: ../../error/erroremptyuser.php');
				}
				$conx->close_conex();

			?>
		</div>
	</div>
	
	<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a><br/>
			Copyright © 2011 - by wiledu[williamcortes10@gmail.com]			
		
	</div>
	</div>
</body>
</html>