INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '1');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '2');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '3');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '4');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '5');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '6');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '7');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '8');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '9');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '10');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '11');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '12');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '13');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '14');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'DESARROLLO FÍSICO Y MOTRIZ', '3', '15');
/*---------------*/
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '1');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '2');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '3');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '4');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '5');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '6');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '7');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '8');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '9');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '10');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '11');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '12');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '13');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '14');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'INTERACCIÓN SOCIAL', '3', '15');
/*---------------*/
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '1');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '2');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '3');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '4');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '5');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '6');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '7');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '8');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '9');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '10');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '11');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '12');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '13');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '14');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'EXPRESIÓN CORPORAL', '3', '15');
/*---------------*/
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '1');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '2');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '3');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '4');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '5');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '6');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '7');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '8');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '9');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '10');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '11');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '12');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '13');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '14');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'FORMACIÓN  Y REALIZACIÓN TÉCNICA', '3', '15');
/*---------------*/
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '1');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '2');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '3');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '4');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '5');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '6');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '7');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '8');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '9');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '10');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '11');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '12');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '13');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '14');
INSERT INTO `appacademy`.`estandares` (`codigo`, `descripcion`, `idmateria_fk`, `grado`) VALUES (NULL, 'RECREACIÓN LÚDICA', '3', '15');