<html>
<head>
<title>JourAcademy::Administrador-Boletin Individual</title>
<link href="../../css/bluedreamtable.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="../../script/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
  $("#sucess").hide();
  $("input").keyup(function(){
  $("#sucess").hide();
  txt=$("input").val();
  al=$("#aniolect").val();
  $.post("boletinindividualresponse.php",{str_search:txt, periodo:$("#periodo").val(), aniolect:al},function(result){
    $("#resultados").html(result);
  });
});
});
function boletinindividual(codigo, periodo, grado, aniolect){
$(document).ready(function(){
  	
	location.href='boletinxest.php?codigo='+codigo+"&periodo="+periodo+"&grado="+grado+"&aniolect="+aniolect;	
  
});

}
</script>
<style>
#filtro,#footer{
margin: 0 auto 0 auto;
width: 750px;
height: auto;
}

</style>
</head>
<body>
	<form id="frmdeldoc" method="post" action="formupdate.php">
	<div id="filtro">
	<label for="txt_filtro">Ingrese codigo, nombre ó apellido:</label>
	<input type="text" id="txt_filtro" />
	<li id="li_7" >
		<label class="description" for="periodo">Periodo </label>
		<div>
		<select  id="periodo" name="periodo"> 
			<option value="1" selected="selected">1</option>
			<option value="2" >2</option>
			<option value="3" >3</option>
			<option value="4" >4</option>

		</select>
		</div><p class="guidelines" id="guide_7"><small>Seleccione el periodo al que pertenece el boletin</small></p> 
	</li>
    <li id="li_15" ><label class='description' for='aniolect'>Año Escolar</label>
        <div>
            <select id='aniolect' name='aniolect'>
            <?php 
                for ($i=(int)date('Y',time()); $i>=2000; $i--) {
                    echo "<option value='$i'>$i</option>";
                }  
            ?>
            </select>
        </div><p class="guidelines" id="guide_7"><small>Seleccione el año escolar</small></p>
        </li>
	<hr>

	<div id="resultados">
	</div>
	<a href="../../indexadmin/index.php" class="large button orange" style="font-size: 14px !important;">Regresar al menu pricipal</a>

	<div id="sucess">
	</div>
	<hr>

	<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a><br/>
			Copyright © 2011 - by wiledu[williamcortes10@gmail.com]
	</div>
	</div>
	</form>
	

</body>
</html>
