<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Generar Boletines por Curso</title>
<link rel="stylesheet" type="text/css" href="../../css/view.css" media="all">
<script type="text/javascript" src="./../script/view.js"></script>
<script type="text/javascript" src="calendar.js"></script><script type="text/javascript" src="view.js"></script><script type="text/javascript" src="../../script/jquery.min.js"></script>
<script type="text/javascript">

function generarplanillas(coddocen,codasig,grado,periodo){
	location.href='boletinxcurso.php?coddocen='+coddocen+'&codasig='+codasig+'&grado='+grado+'&periodo='+periodo;

}
/*$(document).ready(function(){
	
	$("#result").hide();
	$("#coddocen").change(function(){
		$.post("listplancursoresponse.php",{str_search:$('#coddocen').val()},function(data){
			$("#result").html(data);
			$("#result").show();
		});
	});
});*/
</script>

</head>
<body id="main_body" >
<?php
include('../../class/MySqlClass.php');
$conx = new ConxMySQL("localhost","root","","bdaltono");
//mysql_set_charset('utf8',$conx->conexion);

?>
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Generar Boletines - por Curso</a></h1>
		<form id="form_123475" class="appnitro"  method="post" action="boletinxcurso.php">
		<div class="form_description">
			<h2>Generar Boletines - por Curso</h2>
			<p>Elija el curso</p>
		</div>					
			<ul >
		<li id="li_2" >
		<label class="description" for="grado">Clase</label>
		<select class="element select medium" id="grado" name="grado">
		<option value="">-----</option>		
		<?php
			$sql = "SELECT DISTINCT grado FROM clase ORDER BY grado ASC";
			$consulta = $conx->query($sql);
			$band=1;
			while($records = $conx->records_array($consulta)){
				echo "<option value='".utf8_encode($records['grado'])."' >".utf8_encode($records['grado'])."</option>";
			}

		?>
		
		</select>
		<li id="li_7" >
		<label class="description" for="periodo">Periodo </label>
		<div>
		<select class="element select medium" id="periodo" name="periodo"> 
			<option value="1" selected="selected">1</option>
			<option value="2" >2</option>
			<option value="3" >3</option>
			<option value="4" >4</option>

		</select>
		</div><p class="guidelines" id="guide_7"><small>Seleccione el periodo al que pertenece el boletin</small></p> 
		</li>
		<li id="li_8" >
		<label class="description" for="formato">Formato del boletin </label>
		<div>
		<select class="element select medium" id="formato" name="formato"> 
			<option value="f1" selected="selected">Formato1</option>
			<option value="f2" >Formato2</option>
			<option value="f3" >Formato3</option>

		</select>
		</div><p class="guidelines" id="guide_7"><small>Seleccione Formato del Boletin</small></p>
		</li>
        <li id="li_15" ><label class='description' for='aniolect'>Año Escolar</label>
        <div>
            <select id='aniolect' name='aniolect'>
            <?php 
                for ($i=(int)date('Y',time()); $i>=2000; $i--) {
                    echo "<option value='$i'>$i</option>";
                }  
            ?>
            </select>
        </div><p class="guidelines" id="guide_7"><small>Seleccione el año escolar</small></p>
        </li>
		<li class="buttons">
			<span>
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Generar Boletines" />
			</span>
							
		</li>
		</form>	
		<div id="result"></div>
		<a href="../../indexadmin/index.php" class="large button orange" style="font-size: 14px !important;">Regresar al menu pricipal</a>
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a><br/>
			Copyright © 2011 - by wiledu[williamcortes10@gmail.com]
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	<?php
	$conx->close_conex();
	?>
	</body>
</html>